package soopchat

// Reference : https://github.com/wakscord/afreeca
const (
	svc_KEEPALIVE             = 0 /* pingpong */
	svc_LOGIN                 = 1 /* 로그인 핸드쉐이크 */
	svc_JOINCH                = 2 /* 채널 입장 핸드쉐이크 */
	svc_QUITCH                = 3 /* 강제 퇴장 */
	svc_CHUSER                = 4 /* 입장/퇴장 */
	svc_CHATMESG              = 5 /* 채팅 메시지 */
	svc_SETCHNAME             = 6
	svc_SETBJSTAT             = 7
	svc_SETDUMB               = 8 /* 채금 */
	svc_DIRECTCHAT            = 9
	svc_NOTICE                = 10 /* 사용하지 않음 */
	svc_KICK                  = 11 /* 사용하지 않음 */
	svc_SETUSERFLAG           = 12
	svc_SETSUBBJ              = 13
	svc_SETNICKNAME           = 14
	svc_SVRSTAT               = 15 /* 사용하지 않음 */
	svc_NULL_16               = 16 /* 사용하지 않음 */
	svc_CLUBCOLOR             = 17
	svc_SENDBALLOON           = 18 /* 별풍선 */
	svc_ICEMODE               = 19 /* 얼음 */
	svc_SENDFANLETRTRER       = 20
	svc_ICEMODE_EX            = 21 /* 얼음 */ // log상 21, 19 순서임.
	svc_GET_ICEMODE_RELAY     = 22 /* 사용하지 않음 */
	svc_SLOWMODE              = 23 /* 슬로우 모드 */
	svc_RELOADBURNLEVEL       = 24 /* 사용하지 않음 */
	svc_BLINDNICK             = 25 /* 사용하지 않음 */
	svc_MANAGERCHAT           = 26 /* 매니저 채팅, 읽을 수 있는 권리는 매니저 flag 이상만 */
	svc_APPENDDATA            = 27 /* 사용하지 않음 */
	svc_BASEBALLEVENT         = 28 /* 사용하지 않음 */
	svc_PAIDITEM              = 29 /* 사용하지 않음 */
	svc_TOPFAN                = 30 /* 사용하지 않음 */ /* 열혈? */
	svc_SNSMESSAGE            = 31 /* 사용하지 않음 */
	svc_SNSMODE               = 32 /* 사용하지 않음 */
	svc_SENDBALLOONSUB        = 33
	svc_SENDFANLETRTRERSUB    = 34
	svc_TOPFANSUB             = 35 /* 사용하지 않음 */
	svc_BJSTICKERITEM         = 36 /* 사용하지 않음 */
	svc_CHOCOLATE             = 37
	svc_CHOCOLATESUB          = 38
	svc_TOPCLAN               = 39 /* 사용하지 않음 */
	svc_TOPCLANSUB            = 40 /* 사용하지 않음 */
	svc_SUPERCHAT             = 41 /* 사용하지 않음 */
	svc_UPDATETICKET          = 42 /* 사용하지 않음 */
	svc_NOTIGAMERANKER        = 43 /* 사용하지 않음 */
	svc_STARCOIN              = 44
	svc_SENDQUICKVIEW         = 45 /* 퀵 뷰 선물 */
	svc_ITEMSTATUS            = 46 /* 사용하지 않음 */
	svc_ITEMUSING             = 47
	svc_USEQUICKVIEW          = 48
	svc_NOTIFY_POLL           = 50 /* 투표 */
	svc_CHATBLOCKMODE         = 51 /* 사용하지 않음 */
	svc_BDM_ADDBLACKINFO      = 52 /* 블랙리스트..? */
	svc_SETBROADINFO          = 53 /* 사용하지 않음 */
	svc_BAN_WORD              = 54
	svc_SENDADMINNOTICE       = 58 /* 어드민 메시지 */
	svc_FREECAT_OWNER_JOIN    = 65
	svc_BUYGOODS              = 70
	svc_BUYGOODSSUB           = 71
	svc_SENDPROMOTION         = 72 /* 사용하지 않음 */
	svc_NOTIFY_VR             = 74
	svc_NOTIFY_MOBBROAD_PAUSE = 75
	svc_KICK_AND_CANCEL       = 76
	svc_KICK_USERLIST         = 77
	svc_ADMIN_CHUSER          = 78
	svc_CLIDOBAEINFO          = 79
	svc_VOD_BALLOON           = 86
	svc_ADCON_EFFECT          = 87
	svc_SVC_KICK_MSG_STATE    = 90
	svc_FOLLOW_ITEM           = 91 /* 신규 구독 */
	svc_ITEM_SELL_EFFECT      = 92
	svc_FOLLOW_ITEM_EFFECT    = 93 /* 연속 구독 */
	svc_TRANSLATION_STATE     = 94
	svc_TRANSLATION           = 95
	svc_GIFT_TICKET           = 102
	svc_VODADCON              = 103
	svc_BJ_NOTICE             = 104 /* BJ 공지 */
	svc_VIDEOBALLOON          = 105
	svc_STATION_ADCON         = 107
	svc_SENDSUBSCRIPTION      = 108 /* 구독권 선물 */
	svc_OGQ_EMOTICON          = 109
	svc_ITEM_DROPS            = 111
	svc_VIDEOBALLOON_LINK     = 117 /* 사용하지 않음 */
	svc_OGQ_EMOTICON_GIFT     = 118 /* OGQ 이모티콘 선물 */
	svc_AD_IN_BROAD_JSON      = 119
	svc_GEM_ITEMSEND          = 120
	svc_MISSION               = 121 /* 도전 미션 */
	svc_LIVE_CAPTION          = 122
	svc_MISSION_SETTLE        = 125
	svc_SET_ADMIN_FLAG        = 126
	svc_CHUSER_EXTEND         = 127 /* 구독자 리스트 */
	svc_ADMIN_CHUSER_EXTEND   = 128
)
